M48
; DRILL file {KiCad (6.0.2)} date Sat Mar 19 17:29:21 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-03-19T17:29:21+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0941
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1358
%
G90
G05
T1
X4.0881Y-5.2861
T2
X4.4161Y-5.9161
X6.5893Y-5.2861
T0
M30
